version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: 'BankDEV'
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql:/var/lib/mysql

  app:
    depends_on:
      - db
    image: golang:latest
    container_name: bank_services
    volumes:
      - .:/go/src/
    ports:
      - "8078:8080"