version: '3.1'

services:

  db:
    image: postgres:alpine
    container_name: 'BankDEV'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'

  app:
    depends_on:
      - db
    image: golang:latest
    entrypoint: ./Dockerfile
    container_name: bank_services
    volumes:
      - .:/go/src/
    ports:
      - "8078:8080"