// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const addBalanceUser = `-- name: AddBalanceUser :exec
UPDATE accounts SET balance = balance + ? where id = ?
`

type AddBalanceUserParams struct {
	Amount int64
	ID     int32
}

func (q *Queries) AddBalanceUser(ctx context.Context, arg AddBalanceUserParams) error {
	_, err := q.db.ExecContext(ctx, addBalanceUser, arg.Amount, arg.ID)
	return err
}

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO accounts (balance, owner, currency) VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	Balance  int64
	Owner    string
	Currency string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccount, arg.Balance, arg.Owner, arg.Currency)
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance, currency, created_at FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance, currency, created_at FROM accounts ORDER BY id LIMIT ? OFFSET ?
`

type ListAccountsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBalanceUser = `-- name: RemoveBalanceUser :exec
UPDATE accounts SET balance = balance - ? where id = ?
`

type RemoveBalanceUserParams struct {
	Amount int64
	ID     int32
}

func (q *Queries) RemoveBalanceUser(ctx context.Context, arg RemoveBalanceUserParams) error {
	_, err := q.db.ExecContext(ctx, removeBalanceUser, arg.Amount, arg.ID)
	return err
}

const selectLastIntroID = `-- name: SelectLastIntroID :one
select id, owner, balance, currency, created_at FROM accounts WHERE id = last_insert_id()
`

func (q *Queries) SelectLastIntroID(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, selectLastIntroID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
